CREATE TABLE if not exists public.cities
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE if not exists public.departments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    salary_min BIGINT,
    salary_max BIGINT
);

CREATE TABLE if not exists public.leaders
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    salary BIGINT
);

CREATE TABLE if not exists public.employees
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    salary BIGINT
);


CREATE TABLE if not exists public.trips
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date VARCHAR(255) NOT NULL
);



CREATE TABLE if not exists public.deps_trips
(
    department_id bigint not null references public.departments,
    trip_id       bigint not null references public.trips,
    primary key (department_id, trip_id)
);

-- ==================================================================================================

ALTER TABLE public.leaders
    ADD COLUMN department_id BIGINT,
    ADD CONSTRAINT fk_leader_department
        FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.employees
    ADD COLUMN department_id BIGINT,
    ADD CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.departments
    ADD COLUMN leader_id   BIGINT,
    ADD CONSTRAINT fk_department_leader FOREIGN KEY (leader_id) REFERENCES public.leaders (id),
    ADD COLUMN employee_id BIGINT,
    ADD CONSTRAINT fk_department_employee FOREIGN KEY (employee_id) REFERENCES public.employees (id);

